clc;
clear all;
Pb=0.02;
Ao=0.04;
r=0.5:0.2:1.5;
AreaCity=603;
A=38.4;
ang=pi/6;
NoUsersPerCell=A/Ao;
display(NoUsersPerCell);
len1=tan(ang)*r;
len=2*len1;
display(len);
AreaHexagon=3.*r.*len;
display(AreaHexagon);
NoCells=AreaCity./AreaHexagon;
display(NoCells);
NoUser=NoUsersPerCell.*NoCells;
display(NoUser);
plot(r,NoUser,'b');
xlabel('Radius of Hexagon');
ylabel('NoUser');
title('Graph for Estimating total number of Users In City ');
